---
abstract: 'EXPERIMENTAL Declarative Syntax for Catalyst Applications'
author:
  - 'Robert Sedlacek <rs@474.at>'
build_requires:
  Catalyst::Test: 0
  ExtUtils::MakeMaker: 6.42
  FindBin: 0
  Test::More: 0.92
  Test::Output: 0.16
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CatalystX-Declare
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
provides:
  CatalystX::Declare:
    file: lib/CatalystX/Declare.pm
    version: 0.009
  CatalystX::Declare::Keyword::Action:
    file: lib/CatalystX/Declare/Keyword/Action.pm
  CatalystX::Declare::Keyword::Application:
    file: lib/CatalystX/Declare/Keyword/Application.pm
  CatalystX::Declare::Keyword::Component:
    file: lib/CatalystX/Declare/Keyword/Component.pm
  CatalystX::Declare::Keyword::Controller:
    file: lib/CatalystX/Declare/Keyword/Controller.pm
  CatalystX::Declare::Keyword::Model:
    file: lib/CatalystX/Declare/Keyword/Model.pm
  CatalystX::Declare::Keyword::Role:
    file: lib/CatalystX/Declare/Keyword/Role.pm
  CatalystX::Declare::Keyword::View:
    file: lib/CatalystX/Declare/Keyword/View.pm
requires:
  CLASS: 1.00
  Carp: 1.08
  Catalyst: 5.80007
  Class::Inspector: 1.24
  Data::Dump: 1.14
  Devel::Declare: 0.005011
  FindBin: 0
  Moose: 0.89
  MooseX::AttributeHelpers: 0.21
  MooseX::Declare: 0.27
  MooseX::Method::Signatures: 0.21
  MooseX::MethodAttributes: 0.15
  MooseX::Types: 0.17
  Perl6::Junction: 1.40000
  aliased: 0.30
  parent: 0.221
resources:
  bugtracker: http://github.com/phaylon/catalystx-declarative/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/phaylon/catalystx-declarative/tree/master
version: 0.009
