---
abstract: 'EXPERIMENTAL Declarative Syntax for Catalyst Applications'
author:
  - 'Robert Sedlacek <rs@474.at>'
build_requires:
  Catalyst::Test: 0
  ExtUtils::MakeMaker: 6.42
  FindBin: 0
  Test::More: 0.92
  Test::Output: 0.12
configure_requires:
  ExtUtils::MakeMaker: 6.42
  File::Find::Rule: 0
  File::Find::Rule::Perl: 1.09
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CatalystX-Declare
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
provides:
  CatalystX::Declare:
    file: lib/CatalystX/Declare.pm
    version: 0.003
  CatalystX::Declare::Keyword::Action:
    file: lib/CatalystX/Declare/Keyword/Action.pm
  CatalystX::Declare::Keyword::Application:
    file: lib/CatalystX/Declare/Keyword/Application.pm
  CatalystX::Declare::Keyword::Controller:
    file: lib/CatalystX/Declare/Keyword/Controller.pm
  CatalystX::Declare::Keyword::Role:
    file: lib/CatalystX/Declare/Keyword/Role.pm
requires:
  CLASS: 1.00
  Carp: 1.08
  Catalyst: 5.80007
  Class::Inspector: 1.24
  Data::Dump: 1.14
  FindBin: 0
  Moose: 0.88
  MooseX::AttributeHelpers: 0.16
  MooseX::Declare: 0.23
  MooseX::Method::Signatures: 0.16
  MooseX::MethodAttributes: 0.15
  MooseX::Types: 0.16
  Perl6::Junction: 1.40000
  TryCatch: 1.001001
  aliased: 0.22
  parent: 0.221
resources:
  bugtracker: http://github.com/phaylon/catalystx-declarative/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/phaylon/catalystx-declarative/tree/master
version: 0.003
